version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/www"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
