service: MyOnlineBookStore
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  memorySize: 128 # optional, in MB, default is 1024

package:
  individually: true
  exclude:
    - '**'
  include:
    - order/handler.py

functions:
  order:
    handler: order/handler.order
    description: Validate credit score and put order in database.
    reservedConcurrency: 5
    timeout: 2
    tracing: true
    events:
      - sqs: arn:aws:sqs:eu-central-1:438231055637:order.fifo
      - sqs: arn:aws:sqs:eu-central-1:438231055637:order-dlq.fifo
