service: MyOnlineBookStore
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  memorySize: 128 # optional, in MB, default is 1024

package:
  individually: true
  exclude:
    - '**'
  include:
    - order/handler.py

functions:
  order:
    handler: order/handler.order
